init_parm:
  resume: True
  start_epoch: 0
  end_epoch: 300
  num_worker: 16
  input_w: 224
  input_h: 224
train:
  train_set: /home/shihmujan/Desktop/EfficientNet/train_set.txt
  batch_size: 40
vaild:
  vaild_set: /home/shihmujan/Desktop/EfficientNet/vaild_set.txt
  batch_size: 40
test:
  test_set: None
optimizer:
  optim: AdamW
  lr: 0.0001
  weght_decay: 0
  momentum: 0
scheduler:
  scheduler: ExponentialLR
  T_max: 5
  gamma: 0.95
model:
  model_name: gcvit_small
  checkpoint_path: /home/shihmujan/Desktop/EfficientNet/checkpoint/gcvit_small_0.83.pickle
loss:
  loss_function: CrossEntropyLoss
public:
  public_set: /home/shihmujan/Desktop/EfficientNet/public_data.txt
