init_parm:
  resume: True
  start_epoch: 0
  end_epoch: 300
  num_worker: 16
  input_w: 512
  input_h: 512
train:
  train_set: /home/student/Desktop/efficentnet/train_set.txt
  batch_size: 36
vaild:
  vaild_set: /home/student/Desktop/efficentnet/vaild_set.txt
  batch_size: 36
test:
  test_set: None
optimizer:
  optim: RMSprop
  lr: 0.0001
  weght_decay: 0
  momentum: 0
scheduler:
  scheduler: ExponentialLR
  T_max: 5
  gamma: 0.97
model:
  model_name: tiny_vit21m_512
  checkpoint_path: /home/student/Desktop/efficentnet/checkpoint/tiny_vit21m_512_bast_0.90259.pickle
loss:
  loss_function: mix_loss
public:
  public_set: /home/student/Desktop/efficentnet/public_data.txt
